### ISSUE TITLE
Feature Request: Slides?

### ISSUE THREAD

**Issue by IndianTinker** [zachkrall/hydra-workshop#1]
Hello Zach,
This really looks very interesting. Is it possible to add the slides content to the repo as a link or pdf? I am still learning and it will be very useful. Thanks again for this :smile:

**Comment by zachkrall** [comment]
Hi @IndianTinker 
This was a repo for an in person workshop and I don't currently plan on expanding on it. There is some excellent documentation online though: https://github.com/ojack/hydra/blob/master/docs/funcs.md
